### ISSUE TITLE
How to connect to Binance US?

### ISSUE THREAD

**Issue by makuchaku** [binance/binance-cli#2]
Hi there, 
Is there a way to specify to the CLI that I want to connect to Binance US?

In other libraries that I use, I have to set an env variable BINANCE_TLD=US which is picked up by the library.

Thanks!

**Comment by makuchaku** [comment]
Same question for how to setup the CLI to work with Binance Testnet? Thanks!

**Comment by 2pd** [comment]
Thanks for the feedback,  please update to the latest version that support to change the base URL.

```shell
export SERVER=https://testnet.binance.vision
```

As this cli tool is built for .com, it's not officially supporting the .us API.  However you may have a try by change the base url and see if it works for .us as well.
