### ISSUE TITLE
Futures support

### ISSUE THREAD

**Issue by kkoouu** [binance/binance-cli#4]
Please add support for FUTURES, currently "binance-cli account" only returns data for SPOT.

**Comment by 2pd** [comment]
It's in our todo list, however no ETA yet :(

**Comment by hazemdr454** [comment]
> Please add support for FUTURES, currently "binance-cli account" only returns data for SPOT.

**Comment by alplabin** [comment]
A new release that support FUTURES has been made: https://github.com/binance/binance-cli/releases/tag/v1.2.0
