### ISSUE TITLE
feature(client): UI binance cli

### ISSUE THREAD

**Issue by DiegoCascavita** [binance/binance-cli#5]
Currently, the only way to interact with the Binance API client is through a command-line interface. While this may be suitable for advanced users who are comfortable working with command-line tools, it presents a steep learning curve for novice users who are not familiar with command-line interfaces.

By developing a user interface for the Binance API client, it would become much easier for users to interact with the software, regardless of their technical expertise. A user-friendly interface would enable users to easily configure their API keys, view their account balances, monitor market prices, and place orders in a more intuitive way.

**Comment by 2pd** [comment]
Thanks for your suggestion. For users like nice UI, it's recommended to login to binance.com, it provides all functions that users would like from API endpoints.  This repo provides simply commands for some users.
